---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.26.2
    app.quarkus.io/commit-id: fa2b09dcab0e64b40b3997a46d3e907fdad0af3b
    app.quarkus.io/vcs-uri: https://github.com/danieljscosta/cadastroapi-quarkus.git
    app.quarkus.io/build-timestamp: 2025-09-10 - 12:12:01 +0000
  labels:
    app.kubernetes.io/name: cadastroapi-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cadastroapi-quarkus
spec:
  ports:
    - name: http
      nodePort: 30523
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cadastroapi-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.26.2
    app.quarkus.io/commit-id: fa2b09dcab0e64b40b3997a46d3e907fdad0af3b
    app.quarkus.io/vcs-uri: https://github.com/danieljscosta/cadastroapi-quarkus.git
    app.quarkus.io/build-timestamp: 2025-09-10 - 12:12:01 +0000
  labels:
    app.kubernetes.io/name: cadastroapi-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cadastroapi-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cadastroapi-quarkus
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.26.2
        app.quarkus.io/commit-id: fa2b09dcab0e64b40b3997a46d3e907fdad0af3b
        app.quarkus.io/vcs-uri: https://github.com/danieljscosta/cadastroapi-quarkus.git
        app.quarkus.io/build-timestamp: 2025-09-10 - 12:12:01 +0000
      labels:
        app.kubernetes.io/name: cadastroapi-quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/daniel/cadastroapi-quarkus:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: cadastroapi-quarkus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
